"""Shared tokenizer protocol for closed-world tokenizer implementations."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TokenizerProtocol(Protocol):
    @property
    def tokens(self) -> list[str]: ...

    @property
    def pad_id(self) -> int: ...

    @property
    def vocab_size(self) -> int: ...

    @property
    def tokenizer_type(self) -> str: ...

    def encode(self, text: str) -> list[int]: ...

    def decode(self, ids: list[int]) -> str: ...

    def extend(self, text: str) -> "TokenizerProtocol": ...

    def extends(self, base: Any) -> bool: ...

    def to_dict(self) -> dict[str, Any]: ...

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "TokenizerProtocol": ...
